#version 460 core

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0, rgba8) readonly uniform image2D inputImage;
layout(binding = 1, rgba8) writeonly uniform image2D outputImage;

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = imageLoad(inputImage, coords);

    color = vec4(color.b, color.g, color.r, color.a);

    imageStore(outputImage, coords, color);
}
