#version 460 core

#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0, rgba8) uniform image2D images[2];

vec3 linearToSrgb(vec3 linear) {
    vec3 cutoff = step(vec3(0.0031308), linear);
    vec3 lower = linear * 12.92;
    vec3 higher = 1.055 * pow(linear, vec3(1.0 / 2.4)) - 0.055;

    return mix(lower, higher, cutoff);
}

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);

    vec4 color = imageLoad(images[0], coords);

    color.rgb = clamp(linearToSrgb(color.rgb), 0.0, 1.0);

    imageStore(images[1], coords, color);
}
