#version 460 core

#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 32, local_size_y = 32) in;

layout(set = 0, binding = 0, rgba8) uniform image2D images[2];
layout(set = 1, binding = 0, rgba8) uniform image2D ui;

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);

    vec4 bgColor = imageLoad(images[0], coords);
    vec4 fgColor = imageLoad(ui, coords);

    float alpha = fgColor.a;
    vec3 resultColor = mix(bgColor.rgb, fgColor.rgb, alpha);

    vec4 finalColor = vec4(resultColor, 1.0);
    imageStore(images[1], coords, finalColor);
}
